Repository Toblerity/Fiona, pull requests merged in 2018-11, with the labels that each got.

#596 Fixed issue when using field names not supported by layer encoding
  fiona/_err.pyx
  fiona/ogrext.pyx
  fiona/ogrext1.pxd
  fiona/ogrext2.pxd
  tests/test_unicode.py
Labels: bug

#669 Eliminate log messages about ENCODING
  CHANGES.txt
  fiona/__init__.py
  fiona/ogrext.pyx
  tests/test_collection.py
Labels: bug

#677 Set cython language_level=3
  setup.py
Labels: cython

#672 Some type improvements
  fiona/_drivers.pyx
  fiona/_env.pyx
  fiona/_geometry.pxd
  fiona/_geometry.pyx
  fiona/_shim1.pxd
  fiona/_shim2.pxd
  fiona/_shim2.pyx
  fiona/_shim22.pxd
  fiona/_shim22.pyx
  fiona/ogrext.pyx
  fiona/ogrext1.pxd
  fiona/ogrext2.pxd
  setup.py
Labels: bug, cython

#689 Patch os.environ
  .travis.yml
  CHANGES.txt
  fiona/__init__.py
  fiona/_env.pyx
  fiona/env.py
  fiona/fio/env.py
  fiona/ogrext.pyx
Labels: GDAL/OGR, bug
