Repository Toblerity/Fiona, pull requests merged in 2022-12, with the labels that each got.

#1141 ENH: Add support for reading string lists
  fiona/gdal.pxi
  fiona/ogrext.pyx
  fiona/schema.pyx
  tests/test_schema.py
Labels: enhancement

#1168 Remove _loading, copy into __init__
  CHANGES.txt
  fiona/__init__.py
  fiona/collection.py
  fiona/env.py
  fiona/fio/env.py
  fiona/io.py
  fiona/meta.py
  fiona/session.py
  fiona/transform.py
Labels: bug

#1173 Avoid unintentionally catching BrokenPipeError
  CHANGES.txt
  fiona/fio/bounds.py
  fiona/fio/calc.py
  fiona/fio/cat.py
  fiona/fio/collect.py
  fiona/fio/distrib.py
  fiona/fio/dump.py
  fiona/fio/filter.py
  fiona/fio/info.py
  fiona/fio/insp.py
  fiona/fio/load.py
  tests/test_fio_calc.py
Labels: bug, cli
