Repository Toblerity/Fiona, pull requests merged in 2023-10, with the labels that each got.

#1294 fix `OSError: [WinError 87]The parameter is incorrect. : '.' when using PyInstaller
  fiona/__init__.py
Labels: bug

#1276 Preserve the null properties and geometry of a Feature
  .github/workflows/tests.yml
  CHANGES.txt
  environment.yml
  fiona/model.py
  fiona/session.py
  pyproject.toml
  pytest.ini
  requirements-dev.txt
  tests/conftest.py
  tests/test_model.py
Labels: bug

#1303 Release 1.9.5
  CHANGES.txt
  CITATION.cff
  MANIFEST.in
  fiona/__init__.py
  pyproject.toml
Labels: release

#1304 Normalize recursive extra requirements
  pyproject.toml
Labels: packaging

#1308 Create SECURITY.md
  SECURITY.md
Labels: security
