Repository Toblerity/Fiona, pull requests merged in 2023-02, with the labels that each got.

#1186 Run pyupgrade --py37-plus
  benchmark-max.py
  benchmark-min.py
  benchmark.py
  docs/conf.py
  examples/open.py
  examples/orient-ccw.py
  examples/with-descartes.py
  examples/with-pyproj.py
  examples/with-shapely.py
  fiona/__init__.py
  fiona/collection.py
  fiona/drvsupport.py
  fiona/env.py
  fiona/fio/calc.py
  fiona/fio/collect.py
  fiona/fio/env.py
  fiona/fio/load.py
  fiona/fio/options.py
  fiona/fio/rm.py
  fiona/io.py
  fiona/logutils.py
  fiona/meta.py
  fiona/model.py
  fiona/path.py
  fiona/rfc3339.py
  fiona/session.py
  fiona/vfs.py
  scripts/check_deprecated.py
  scripts/check_urls.py
  tests/conftest.py
  tests/test__env.py
  tests/test_bytescollection.py
  tests/test_collection.py
  tests/test_crs.py
  tests/test_cursor_interruptions.py
  tests/test_datetime.py
  tests/test_drivers.py
  tests/test_encoding.py
  tests/test_env.py
  tests/test_feature.py
  tests/test_fio_calc.py
  tests/test_fio_cat.py
  tests/test_fio_dump.py
  tests/test_fio_info.py
  tests/test_fio_load.py
  tests/test_fio_ls.py
  tests/test_fio_rm.py
  tests/test_listing.py
  tests/test_model.py
  tests/test_multiconxn.py
  tests/test_non_counting_layer.py
  tests/test_remove.py
  tests/test_rfc3339.py
  tests/test_schema.py
  tests/test_subtypes.py
  tests/test_topojson.py
  tests/test_unicode.py
  tests/test_vfs.py
Labels: refactor, automation

#1193 TST: don't rely on exact order in listdir tests
  tests/test_listing.py
Labels: bug, tests

#1205 Ensure OGR geometries are cleaned up in Iterator._next()
  CHANGES.txt
  fiona/ogrext.pyx
  scripts/travis_gdal_install.sh
Labels: bug
