Repository Toblerity/Fiona, pull requests merged in 2024-09, with the labels that each got.

#1432 Rel 1.10.0
  CHANGES.txt
  CITATION.cff
  CREDITS.txt
  fiona/__init__.py
  fiona/model.py
  pyproject.toml
  requirements.txt
  setup.cfg
  tests/test_model.py
Labels: release

#1445 Avoid printing representations of NULL objects
  CHANGES.txt
  Makefile
  fiona/crs.pyx
  tests/test_crs.py
Labels: bug

#1448 Fix typos
  CHANGES.txt
  appveyor.yml
  docs/cli.rst
  docs/conf.py
  fiona/__init__.py
  fiona/_path.py
  fiona/_vsiopener.pyx
  fiona/drvsupport.py
  fiona/env.py
  fiona/fio/collect.py
  fiona/fio/dump.py
  fiona/inspector.py
  fiona/logutils.py
  fiona/meta.py
  fiona/session.py
  fiona/vfs.py
  tests/test_bigint.py
  tests/test_datetime.py
Labels: bug, docs

#1449 Rel 1.10.1
  CHANGES.txt
  appveyor.yml
  docs/cli.rst
  docs/conf.py
  fiona/__init__.py
  fiona/_path.py
  fiona/_vsiopener.pyx
  fiona/drvsupport.py
  fiona/env.py
  fiona/fio/collect.py
  fiona/fio/dump.py
  fiona/inspector.py
  fiona/logutils.py
  fiona/meta.py
  fiona/session.py
  fiona/vfs.py
  tests/test_bigint.py
  tests/test_datetime.py
Labels: release
